// Generated by gencpp from file beginner/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_MESSAGE_ADDTWOINTS_H
#define BEGINNER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <beginner/AddTwoIntsRequest.h>
#include <beginner/AddTwoIntsResponse.h>


namespace beginner
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace beginner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner::AddTwoInts > {
  static const char* value()
  {
    return "beginner/AddTwoInts";
  }

  static const char* value(const ::beginner::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::beginner::AddTwoInts >
template<>
struct MD5Sum< ::beginner::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner::AddTwoInts >::value();
  }
  static const char* value(const ::beginner::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner::AddTwoIntsRequest> should match
// service_traits::DataType< ::beginner::AddTwoInts >
template<>
struct DataType< ::beginner::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner::AddTwoInts >::value();
  }
  static const char* value(const ::beginner::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::beginner::AddTwoInts >
template<>
struct MD5Sum< ::beginner::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner::AddTwoInts >::value();
  }
  static const char* value(const ::beginner::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner::AddTwoIntsResponse> should match
// service_traits::DataType< ::beginner::AddTwoInts >
template<>
struct DataType< ::beginner::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner::AddTwoInts >::value();
  }
  static const char* value(const ::beginner::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_MESSAGE_ADDTWOINTS_H
